### ISSUE TITLE
Crashes on dedicated servers

### ISSUE THREAD

**Issue by moritzruth** [davioliva16/create-aquatic-ambitions#2]
A dedicated server with this mod installed crashes during the startup process.

I assume this is due to the mod trying to access `com.jozufozu.flywheel.core.PartialModel` from Flywheel which is not available in (dedicated) server environments.

<details>
<summary>Stacktrace</summary>

```java
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'create_aquatic_ambitions'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.11.jar:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.15.11-launcher.1.0.1.jar:1.0.1]
Caused by: java.lang.NoClassDefFoundError: com/jozufozu/flywheel/core/PartialModel
	at net.davio.create_aquatic_ambitions.entry.CCAPartials.block(CCAPartials.java:14) ~[create_aquatic_ambitions_fabric-1.1.1+1.20.1.jar:?]
	at net.davio.create_aquatic_ambitions.entry.CCAPartials.<clinit>(CCAPartials.java:10) ~[create_aquatic_ambitions_fabric-1.1.1+1.20.1.jar:?]
	at net.davio.create_aquatic_ambitions.CreateAquaticAmbitions.onInitialize(CreateAquaticAmbitions.java:44) ~[create_aquatic_ambitions_fabric-1.1.1+1.20.1.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
	... 7 more
Caused by: java.lang.ClassNotFoundException: com.jozufozu.flywheel.core.PartialModel
	at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.davio.create_aquatic_ambitions.entry.CCAPartials.block(CCAPartials.java:14) ~[create_aquatic_ambitions_fabric-1.1.1+1.20.1.jar:?]
	at net.davio.create_aquatic_ambitions.entry.CCAPartials.<clinit>(CCAPartials.java:10) ~[create_aquatic_ambitions_fabric-1.1.1+1.20.1.jar:?]
	at net.davio.create_aquatic_ambitions.CreateAquaticAmbitions.onInitialize(CreateAquaticAmbitions.java:44) ~[create_aquatic_ambitions_fabric-1.1.1+1.20.1.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
	... 7 more
```

</details>

Thank you for creating this mod.

**Comment by davioliva16** [comment]
I've split PartialModels init to only happen on client initialization (on Fabric). I'll test it and maybe release a fix for it this weekend
